Implement merge so testMerge works. Bug in BinarySearch so it does not work failure trace:
	e05mergesort.MergeSortTest
	testIntegerListWithTwoEntries(e05mergesort.MergeSortTest)
	java.lang.AssertionError: Compare mergeSort() with Collections.sort()
	Expected: is <[1, 2]>
	     got: <[1]>

	testIntegerListOnSheet(e05mergesort.MergeSortTest)
	java.lang.AssertionError: Compare mergeSort() with Collections.sort()
	Expected: is <[1, 2, 3, 7, 9]>
	     got: <[1]>