Add arrayUsersBorrowingBooks() & arrayAllUsers... methods (1.9). To interface and as stub methods in Impl.
Write JUnit testArrayUsersMethods this fails as it should,
with trace:

java.lang.AssertionError: Initially have no users, arrayAllUsers should empty: actual array was null
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:66)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:34)
	at org.junit.Assert.internalArrayEquals(Assert.java:414)
	at org.junit.Assert.assertArrayEquals(Assert.java:166)
	at library2.LibraryImplTest.TestArrayUsersMethods(LibraryImplTest.java:284)
        ....