initial implementation of Patient class without the required valid age requirement.
JUnit tests fail with trace:
PatientTest
e04morepatients.PatientTest
testSupplyingAgeInsteadOfYear(e04morepatients.PatientTest)
java.lang.AssertionError: Constructtor failed to throw a IllegalArgumentException  for a patient born in 0 - so 2015 years old!

testNegativeAge(e04morepatients.PatientTest)
java.lang.AssertionError: Constructtor failed to throw a IllegalArgumentException for a patient born in 2020