add method returnBook(Book book) to Library.
Test in testBookReturn in LibraryImplTest.

The first stub implementation of returnBook does nothing so we get
get an assertion Error as we should:

java.lang.AssertionError: After returning one book, user has one borrowed expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.failNotEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:126)
	at org.junit.Assert.assertEquals(Assert.java:470)
	at library2.LibraryImplTest.testBookReturn(LibraryImplTest.java:206)
        ....