alter setMaxBooksPerUser() to return array. Initial stub implementation test fails as it should with a trace:
java.lang.AssertionError: Set maxBooks per user to 1, expect to get Lisa and Maggie in offenders array: actual array was null
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:66)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:34)
	at org.junit.Assert.internalArrayEquals(Assert.java:414)
	at org.junit.Assert.assertArrayEquals(Assert.java:166)
	at library2.LibraryImplTest.testLowerMaxBooksPerUser(LibraryImplTest.java:412)