Stub initial implementation. Fails JUnit test with trace:
PrimeDivisorListImplTest
e05primedivisorlist.PrimeDivisorListImplTest
testAddNonPrimeProducesException(e05primedivisorlist.PrimeDivisorListImplTest)
java.lang.AssertionError: Adding 4 as a prime failed to produce an IllegalArgumentException

testSheetExample(e05primedivisorlist.PrimeDivisorListImplTest)
java.lang.AssertionError: Adding 7,3,2,3 produces correct .toString()
Expected: is "[ 2 * 3^2 *7 = 126 ]"
     got: "debug stub method PrimeDivisorListImpl.toString() needs to be written!"

testOKRemove(e05primedivisorlist.PrimeDivisorListImplTest)
java.lang.AssertionError: Adding 7,3,2,3 and removing 7 produces correct .toString()
Expected: is "[ 2 * 3^2 = 18 ]"
     got: "debug stub method PrimeDivisorListImpl.toString() needs to be written!"

testBadRemove(e05primedivisorlist.PrimeDivisorListImplTest)
java.lang.AssertionError: .remove(13) from a list that does not contain 13 failed to produce an IllegalArgumentException

testAddValidPrime(e05primedivisorlist.PrimeDivisorListImplTest)
java.lang.AssertionError: Adding a single prime 3 produces correct .toString()
Expected: is "[ 3 = 3 ]"
     got: "debug stub method PrimeDivisorListImpl.toString() needs to be written!"