Implement return a copy of the list if it has... one or zero elements. Add tests for lists with more than one element these fail:
JUnit output
	testIntegerListWithTwoEntries(e05mergesort.MergeSortTest)
	java.lang.AssertionError: Compare mergeSort() with Collections.sort()
	Expected: is <[1, 2]>
	     got: null
Console output:
	debug MergeSort needs to sort list [2, 1]

JUnit output
	testIntegerListOnSheet(e05mergesort.MergeSortTest)
	java.lang.AssertionError: Compare mergeSort() with Collections.sort()
	Expected: is <[1, 2, 3, 7, 9]>
	     got: null
Console output:
	debug MergeSort needs to sort list [3, 7, 2, 9, 1]