add merge() method to do the required merge. And a JUnit "testMerge" that fails as it should on the initial "stub" method with trace:
	java.lang.AssertionError: merge [1, 3] with [2, 4, 5]
	Expected: is <[1, 2, 3, 4, 5]>
	     got: null